### DISCUSSION TITLE
iOS Safari 底部被遮挡问题

### DISCUSSION THREAD

**Discussion by jiakun-zhao** [jiakun-zhao/jiakun-zhao#22] [Record]
#### 100vh 的错误

在元素使用 100vh 时，实际可见区域会小于预期（或出现滚动条），即部分内容会被 Safari 所遮挡。

#### 解决方案

使用 `window.innerHeight` 来设置元素的高度，VueUse 的 `useWindowSize` 方法也可。

#### 扩展

iOS 小黑条的修复

HTML:

```html
<meta name="viewport" content="... viewport-fit=cover" />
```

CSS:

```css
body {
    padding-bottom: constant(safe-area-inset-bottom); /* 兼容 iOS < 11.2 */
    padding-bottom: env(safe-area-inset-bottom); /* 兼容 iOS > 11.2 */
}
```
