### DISCUSSION TITLE
Vue Router 顶部跳转进度条

### DISCUSSION THREAD

**Discussion by jiakun-zhao** [jiakun-zhao/jiakun-zhao#31] [Record]
1. 安装插件

```bash
pnpm add nprogress
```

2. 使用

```ts
import NProgress from 'nprogress'
import 'nprogress/nprogress.css'

const router = createRouter({ history: createWebHistory(), routes })

NProgress.configure({ showSpinner: false }) // 禁⽤右侧进度环

router.beforeEach(async (to, from, next) => {
    NProgress.start()
    next()
})
router.afterEach(() => NProgress.done())

app.use(router)
```

3. 样式修改

```css
#nprogress  .bar {
    background: var(--s1) !important;
}
```
